### ISSUE TITLE
安装版新建标签页的时候闪退

### ISSUE THREAD

**Issue by long45343** [Moran-Studio/AutoArknights#5]
![image](https://user-images.githubusercontent.com/51872789/89363157-1a566f00-d702-11ea-89a4-593086d89ac2.png)
用的是windows10 20H2

**Comment by basket-ball** [comment]
试试重新以管理员身份运行，解决方案 https://blog.csdn.net/shuiyixin/article/details/90370387

**Comment by long45343** [comment]
可以了，谢谢。
